[mypy]
python_version = 3.11
plugins = pydantic.mypy
ignore_missing_imports = True
no_implicit_optional = True
warn_redundant_casts = True
warn_unused_ignores = False
check_untyped_defs = True

[mypy-tests.*]
disable_error_code = no-untyped-def

[pydantic-mypy]
init_forbid_extra = True
init_typed = True
